# Generated by Django 5.2.17 on 2026-09-08 15:41

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='join_date',
            field=models.DateField(default=api.models.get_current_date),
        ),
        migrations.AlterField(
            model_name='dailycheckin',
            name='date',
            field=models.DateField(default=api.models.get_current_date),
        ),
        migrations.AlterField(
            model_name='workoutcompletion',
            name='date',
            field=models.DateField(default=api.models.get_current_date),
        ),
    ]
